import os
import shutil
import tempfile
import time
from pathlib import Path

import docker
from docker.errors import ContainerError, DockerException

# Name of the Docker image built from Dockerfile.sandbox
SANDBOX_IMAGE = "data-cleaning-sandbox"

# Directory where successful output CSVs will be stored
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


def run_code_in_docker(code: str, input_csv_path: str) -> dict:
    """
    Execute LLM-generated Python code safely inside an isolated Docker container.

    Parameters
    ----------
    code : str
        Python code generated by the LLM.

    input_csv_path : str
        Path to the uploaded CSV file.

    Returns
    -------
    dict
        {
            "success": bool,
            "output_path": str | None,
            "stdout": str,
            "stderr": str,
            "exit_code": int,
            "execution_time": float
        }
    """

    client = docker.from_env()

    temp_dir = tempfile.mkdtemp()

    container = None

    try:
        # ------------------------------------------------------------
        # Create temporary files
        # ------------------------------------------------------------
        script_path = os.path.join(temp_dir, "generated_script.py")

        output_dir = os.path.join(temp_dir, "output")
        os.makedirs(output_dir, exist_ok=True)

        with open(script_path, "w", encoding="utf-8") as f:
            f.write(code)

        # ------------------------------------------------------------
        # Mount host paths into Docker container
        # ------------------------------------------------------------
        volumes = {
            os.path.abspath(input_csv_path): {
                "bind": "/sandbox/input.csv",
                "mode": "ro",
            },
            os.path.abspath(script_path): {
                "bind": "/sandbox/generated_script.py",
                "mode": "ro",
            },
            os.path.abspath(output_dir): {
                "bind": "/sandbox/output",
                "mode": "rw",
            },
        }

        # ------------------------------------------------------------
        # Start timer
        # ------------------------------------------------------------
        start_time = time.perf_counter()

        # ------------------------------------------------------------
        # Launch isolated container
        # ------------------------------------------------------------
        container = client.containers.run(
            image=SANDBOX_IMAGE,
            command="python /sandbox/generated_script.py",
            detach=True,
            network_mode="none",
            mem_limit="256m",
            nano_cpus=1_000_000_000,
            working_dir="/sandbox",
            read_only=True,
            volumes=volumes,
        )

        try:
            result = container.wait(timeout=10)
            exit_code = result["StatusCode"]

        except Exception:
            container.kill()
            exit_code = -1

        execution_time = round(
            time.perf_counter() - start_time,
            3
        )

        # ------------------------------------------------------------
        # Capture logs
        # ------------------------------------------------------------
        stdout = container.logs(stdout=True, stderr=False).decode("utf-8")

        stderr = container.logs(stdout=False, stderr=True).decode("utf-8")

        # ------------------------------------------------------------
        # Check output
        # ------------------------------------------------------------
        generated_output = os.path.join(output_dir, "output.csv")

        success = (
            exit_code == 0
            and os.path.exists(generated_output)
        )

        final_output_path = None

        if success:
            timestamp = int(time.time())

            final_output_path = OUTPUT_DIR / f"output_{timestamp}.csv"

            shutil.copy2(
                generated_output,
                final_output_path
            )

        return {
            "success": success,
            "output_path": str(final_output_path) if success else None,
            "stdout": stdout,
            "stderr": stderr,
            "exit_code": exit_code,
            "execution_time": execution_time,
        }

    except (ContainerError, DockerException) as e:

        return {
            "success": False,
            "output_path": None,
            "stdout": "",
            "stderr": str(e),
            "exit_code": -1,
            "execution_time": 0.0,
        }

    finally:

        # Always remove container
        if container is not None:
            try:
                container.remove(force=True)
            except Exception:
                pass

        # Always remove temporary workspace
        shutil.rmtree(temp_dir, ignore_errors=True)