from typing import List, Optional

from pydantic import BaseModel, Field


class InspectResult(BaseModel):
    """
    Result returned by inspect_dataframe().
    """

    total_rows: int = Field(
        ...,
        description="Total number of rows in the dataset."
    )

    total_columns: int = Field(
        ...,
        description="Total number of columns in the dataset."
    )

    column_names: List[str] = Field(
        ...,
        description="List of column names."
    )

    column_dtypes: dict[str, str] = Field(
        ...,
        description="Mapping of column names to pandas data types."
    )

    missing_values: dict[str, int] = Field(
        ...,
        description="Mapping of column names to their missing value counts."
    )

    preview: str = Field(
        ...,
        description="String representation of the first few rows."
    )

    summary: str = Field(
        ...,
        description="Human-readable dataset summary for the LLM."
    )


class CodeGenerationResult(BaseModel):
    """
    Result returned by generate_cleaning_code().
    """

    generated_code: str = Field(
        ...,
        description="Python pandas code generated by the LLM."
    )


class ExecutionResult(BaseModel):
    """
    Result returned by execute_generated_code_reliably().
    """

    success: bool = Field(
        ...,
        description="Whether execution completed successfully."
    )

    generated_code: str = Field(
        ...,
        description="The final code that was executed."
    )

    output_path: Optional[str] = Field(
        default=None,
        description="Path to the cleaned CSV file."
    )

    stdout: str = Field(
        default="",
        description="Captured standard output."
    )

    stderr: str = Field(
        default="",
        description="Captured standard error."
    )

    exit_code: int = Field(
        ...,
        description="Process exit code."
    )

    execution_time: float = Field(
        ...,
        description="Execution time in seconds."
    )

    attempts: int = Field(
        ...,
        description="Number of execution attempts performed."
    )

    message: Optional[str] = Field(
        default=None,
        description="Additional status or failure message."
    )


class ValidationResult(BaseModel):
    """
    Result returned by validate_output().
    """

    warnings: List[str] = Field(
        default_factory=list,
        description="Validation warnings. Empty if no issues were found."
    )