import re
import pandas as pd

from langchain.tools import tool
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

from backend.sandbox import run_code_in_docker


@tool
def inspect_dataframe(file_path: str) -> str:
    """
    Read a CSV file and return a concise textual summary
    suitable for LLM context.
    """

    df = pd.read_csv(file_path)

    summary = []

    summary.append(f"Total Rows: {len(df)}")
    summary.append(f"Total Columns: {len(df.columns)}")

    summary.append("\nColumns and Data Types:")

    for column, dtype in df.dtypes.items():
        summary.append(f"- {column}: {dtype}")

    summary.append("\nMissing Values:")

    for column, count in df.isnull().sum().items():
        summary.append(f"- {column}: {count}")

    summary.append("\nFirst 20 Rows:")

    summary.append(df.head(20).to_string())

    return "\n".join(summary)


@tool
def generate_cleaning_code(schema_summary: str, user_instruction: str) -> str:
    """
    Generate Python pandas code that cleans a CSV according to
    the user's instruction.
    """

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """
You are an expert Python data engineer.

Write ONLY executable Python code.

Rules:
1. Read the dataset from '/sandbox/input.csv'
2. Save the cleaned dataset to '/sandbox/output/output.csv'
3. Perform ONLY the transformation requested by the user
4. Import ONLY:
   - pandas
   - numpy
   - re
5. Do NOT print explanations.
6. Do NOT use markdown.
7. Do NOT wrap the code inside ```python or ``` fences.
8. The final script must be directly executable.
                """,
            ),
            (
                "human",
                """
Dataset Summary:

{schema_summary}

User Instruction:

{user_instruction}
                """,
            ),
        ]
    )

    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0,
    )

    parser = StrOutputParser()

    # LCEL Chain
    chain = prompt | llm | parser

    generated_code = chain.invoke(
        {
            "schema_summary": schema_summary,
            "user_instruction": user_instruction,
        }
    )

    # Remove markdown fences if the model adds them anyway
    generated_code = re.sub(
        r"^```(?:python)?\s*",
        "",
        generated_code.strip(),
        flags=re.IGNORECASE,
    )

    generated_code = re.sub(
        r"\s*```$",
        "",
        generated_code,
    )

    return generated_code


@tool
def execute_generated_code(code: str, input_csv_path: str) -> dict:
    """
    Execute LLM-generated Python code inside the Docker sandbox.

    Parameters
    ----------
    code : str
        Python code generated by the LLM.

    input_csv_path : str
        Path to the uploaded CSV file on the host machine.

    Returns
    -------
    dict
        {
            "success": bool,
            "output_path": str | None,
            "stdout": str,
            "stderr": str,
            "exit_code": int,
            "execution_time": float
        }
    """

    return run_code_in_docker(
        code=code,
        input_csv_path=input_csv_path,
    )